// SPDX-FileCopyrightText: 2026 missing-foss
// SPDX-License-Identifier: GPL-3.0-or-later
// #82: parseTrackRefs/parseDeleteRefs/errorMessage are private on ApiClient —
// exercised here through the public surface (getChanges) against a real local
// HTTP server standing in for trobar-server, same pattern as
// EnrollmentWizardTest/SettingsScreenTest. ApiClient itself needs a real
// Context (string resources for its error messages), so this runs
// instrumented rather than as a plain JVM test.

package com.mfoss.trobar

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.json.JSONException
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ApiClientTest {
    private val context = InstrumentationRegistry.getInstrumentation().targetContext
    private lateinit var server: MockWebServer
    private lateinit var api: ApiClient

    @Before
    fun startServer() {
        server = MockWebServer()
        server.start()
        api = ApiClient(context, server.url("/").toString(), "test-token")
    }

    @After
    fun stopServer() {
        server.shutdown()
    }

    @Test
    fun getChangesParsesTrackAndDeleteRefsAndPlaylists() {
        server.enqueue(
            MockResponse().setResponseCode(200).setBody(
                """
                {
                  "to_download": [
                    {"track_id": 1, "relative_path": "Artist/Album/01 - Song.flac", "size": 12345},
                    {"track_id": 2, "relative_path": "Artist/Album/02 - Other.mp3", "size": 999, "transcode": true}
                  ],
                  "to_delete": [
                    {"track_id": 3, "relative_path": "Old/Track.flac"}
                  ],
                  "downloaded": [
                    {"track_id": 4, "relative_path": "Already/Here.flac", "size": 42}
                  ],
                  "playlists": [
                    {"name": "Favorites", "filename": "Favorites.m3u8", "content": "# Generated by Trobar\n"}
                  ]
                }
                """.trimIndent(),
            ),
        )

        val changes = api.getChanges()

        assertEquals(2, changes.toDownload.size)
        assertEquals(1L, changes.toDownload[0].trackId)
        assertEquals("Artist/Album/01 - Song.flac", changes.toDownload[0].relativePath)
        assertEquals(12345L, changes.toDownload[0].size)
        assertFalse(changes.toDownload[0].transcode) // absent in JSON -> defaults false
        assertTrue(changes.toDownload[1].transcode) // present and true in JSON

        assertEquals(1, changes.toDelete.size)
        assertEquals(3L, changes.toDelete[0].trackId)
        assertEquals("Old/Track.flac", changes.toDelete[0].relativePath)

        assertEquals(1, changes.downloaded.size)
        assertEquals(4L, changes.downloaded[0].trackId)

        assertEquals(1, changes.playlists.size)
        assertEquals("Favorites", changes.playlists[0].name)
    }

    @Test
    fun getChangesWithNoOptionalArraysReturnsEmptyLists() {
        server.enqueue(MockResponse().setResponseCode(200).setBody("{}"))

        val changes = api.getChanges()

        assertTrue(changes.toDownload.isEmpty())
        assertTrue(changes.toDelete.isEmpty())
        assertTrue(changes.downloaded.isEmpty())
        assertTrue(changes.playlists.isEmpty())
    }

    @Test
    fun getChangesWithMalformedTrackRefThrows() {
        // "size" is required by parseTrackRefs (o.getLong("size")) — a
        // server response missing it must fail loudly, not silently coerce.
        server.enqueue(
            MockResponse().setResponseCode(200).setBody(
                """{"to_download": [{"track_id": 1, "relative_path": "x.flac"}]}""",
            ),
        )

        try {
            api.getChanges()
            fail("expected a JSONException for the missing 'size' field")
        } catch (ignored: JSONException) {
            // expected
        }
    }

    @Test
    fun errorResponseWithJsonErrorFieldSurfacesServerMessage() {
        server.enqueue(
            MockResponse().setResponseCode(500).setBody("""{"error": "Server exploded"}"""),
        )

        try {
            api.getChanges()
            fail("expected an IOException")
        } catch (e: java.io.IOException) {
            assertEquals("Server exploded", e.message)
        }
    }

    @Test
    fun errorResponseWithNoJsonBodyFallsBackToGenericMessage() {
        server.enqueue(MockResponse().setResponseCode(503))

        val expected = context.getString(R.string.api_error_generic, "changes", 503)
        try {
            api.getChanges()
            fail("expected an IOException")
        } catch (e: java.io.IOException) {
            assertEquals(expected, e.message)
        }
    }

    @Test
    fun unauthorizedResponseThrowsUnauthorizedExceptionWithServerMessage() {
        server.enqueue(
            MockResponse().setResponseCode(401).setBody("""{"error": "Token no longer valid"}"""),
        )

        try {
            api.getChanges()
            fail("expected an UnauthorizedException")
        } catch (e: UnauthorizedException) {
            assertEquals("Token no longer valid", e.message)
        }
    }
}
